api/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include
from django.views.generic import RedirectView
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic import TemplateView
from api import views

app_name = 'api'
urlpatterns = [
    path('autor/', views.autor_api_view, name='autor-api'),
    path('autor/<int:pk>', views.autor_detail_view, name='autor_detail_view'),
]

catalog/urls.py
from django.urls import include, path
from . import views

urlpatterns = [
    path('', views.index, name='index'),

# Libros
    path('books/', views.BookListView.as_view(), name='books'),
    path('book/<int:pk>', views.BookDetailView.as_view(), name='book-detail'),
    path('mybooks/', views.LoanedBooksByUserListView.as_view(), name='my-borrowed'),
    path('book/<uuid:pk>/renew/', views.renew_book_librarian, name='renew-book-librarian'),
    path('book/create/', views.BookCreate.as_view(), name='book-create'),
    path('book/<int:pk>/crearPDF', views.crearPDF, name='crear-pdf'),
    path('book/<int:pk>/update/', views.BookUpdateView.as_view(), name='book-update'),
    path('book/<int:pk>/delete/', views.BookDeleteView.as_view(), name='book-delete'),


# Autores
    path('authors/', views.AuthorListView.as_view(), name='authors'),
    path('author/<int:pk>', views.AuthorDetailView.as_view(), name='author-detail'),
    path('author/create/', views.AuthorCreateView.as_view(), name='author-create'),
    path('author/<int:pk>/update/', views.AuthorUpdateView.as_view(), name='author-update'),
    path('author/<int:pk>/delete/', views.AuthorDeleteView.as_view(), name='author-delete'),
    path('myalbums/', views.AlbumesPrestadosOReservados.as_view(), name='albumes-prestados'),


# JSON
    path('mas/<str:id1>/<str:id2>', views.mas, name='dosJSON'),
    path('mas/<int:id>', views.mas2, name='librosJSON'),
    path('get/', views.respuestaGET, name='respuestaGET'),
    path('JsonFinder/', views.JsonFinder, name='json-finder'),

# Examen 10-12-2024 Javier
    path('listadoLectores/', views.descarga, name='lector_list'),
    path('listadoEncuestas/', views.ListadoEncuestasView.as_view(), name='encuesta_list'),
    path('listadoEncuestas/<int:id>', views.descargaEncuesta, name='descargaEncuesta'),

# Calculadora
    path('calculadora/', views.calculadora, name='calculadora'),

# Álbumes
    path('formulario/', views.formulario, name='formulario'),
    path('albums/', views.AlbumListView.as_view(), name='albums'),
    path('album/<int:pk>', views.AlbumDetailView.as_view(), name='album-detail'),
    path('album/<int:pk>/update/', views.AlbumUpdateView.as_view(), name='album-update'),
    path('album/<int:pk>/delete/', views.AlbumDeleteView.as_view(), name='album-delete'),

# Usuario X
    path('alta/', views.altaUsuarioX, name='darAltaUsuarioX'),
    path('alta/<int:pk>/update/', views.UsuarioXUpdateView.as_view(), name='usuariox-update'),
    path('alta/<int:pk>/delete/', views.UsuarioXDeleteView.as_view(), name='usuariox-delete'),

# API RESTful
    path('v1/api/', include('api.urls', namespace='api')),

# Reserva
    path('reservar/', views.reservar, name='reservar'),


]

locallibrary/urls.py
from catalog import views
from django.contrib import admin
from django.urls import path
from django.urls import include
from django.views.generic import RedirectView
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic import TemplateView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('catalog/', include('catalog.urls')),
    path('', RedirectView.as_view(url='catalog/')),
    path('catalog/', include('catalog.urls')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

urlpatterns += [
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/new-account', views.nuevoUsuario, name="new_account"),
    path('accounts/logouts/', TemplateView.as_view(template_name="registration/logout.html"), name="logouts"),
    path('api/', include('api.urls')),
    path('api-auth/', include('rest_framework.urls'))
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

catalog/views.py
import os
from django.shortcuts import render
from django.http import HttpRequest
import datetime
from locallibrary.settings import BASE_DIR
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.contrib.auth.decorators import login_required
from django.urls import reverse_lazy
from .models import *
from django.http import JsonResponse
from django.views.decorators.clickjacking import *
from django.core import serializers
from django.core.paginator import Paginator
from django.http import HttpResponse
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.decorators.clickjacking import xframe_options_sameorigin
from django.utils.decorators import method_decorator
import sqlite3
from django.utils import timezone
from reportlab import *
import io
from reportlab.pdfgen import canvas
from django.http import FileResponse
from reportlab.platypus import Image
from reportlab.lib.utils import ImageReader
from django.conf import settings



# Create your views here

from django.contrib.auth.decorators import permission_required


""" 
PÁGINA 3 EN EL DOCUMENTO
"""
def index(request):
    """
    Función vista para la página inicio del sitio.
    """
    # Genera contadores de algunos de los objetos principales
    num_books=Book.objects.all().count()
    num_instances=BookInstance.objects.all().count()
    # Libros disponibles (status = 'a')
    num_instances_available=BookInstance.objects.filter(status__exact='a').count()
    num_authors=Author.objects.count()  # El 'all()' esta implícito por defecto.

    # Renderiza la plantilla HTML index.html con los datos en la variable contexto
    num_visits = request.session.get('num_visits', 0)
    num_visits += 1
    request.session['num_visits'] = num_visits

    num_albums = Album.objects.all().count()

    num_users = User.objects.all().count()

    num_albuminst = AlbumInstance.objects.all().count()

    context = {
        'num_books':num_books,
        'num_instances':num_instances,
        'num_instances_available':num_instances_available,
        'num_authors':num_authors,
        'num_visits':num_visits,
        'num_albums':num_albums,
        'num_users':num_users,
        'num_albuminst':num_albuminst,
    }

    # Carga la plantilla index.html con la información adicional en la variable context.
    return render(request, 'index.html', context=context)

from django.views import generic


""" 
PÁGINA 4 EN EL DOCUMENTO
"""
""" Libros """
class BookListView(generic.ListView):
    model = Book
    paginate_by = 10
    paginate_orphans = 1

    def get_queryset(self):
        resultado = super().get_queryset()
        busqueda = self.request.GET.get("busqueda")
        if busqueda:
            resultado = Book.objects.filter(title__icontains=busqueda)
            return resultado
        return super().get_queryset()


    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['now'] = timezone.now()
        return context

class BookDetailView(generic.DetailView):
    model = Book

@method_decorator(permission_required('catalog.can_add_book'), name='dispatch')
class BookCreate(LoginRequiredMixin, CreateView):
    model = Book
    fields = '__all__'

@login_required
@permission_required('catalog.can_change_book')
def crearPDF(request, pk):
    
    libro = Book.objects.get(pk=pk)

    archivo = io.BytesIO()

    pdf = canvas.Canvas(archivo)

    pdf.drawString(15, 800, f'Title: {libro.title}')
    pdf.drawString(15, 780, f'Author: {libro.author}')
    pdf.drawString(15, 760, f'Summary: {libro.summary}')
    pdf.drawString(15, 740, f'ISBN: {libro.isbn}')
    genre = str(libro.genre)
    if genre == 'catalog.Genre.None':
        pdf.drawString(15, 720, f'No genre at all')
    else:
        pdf.drawString(15, 720, f'Genre: {libro.genre}')
    pdf.drawString(15, 700, f'Language: {libro.language}')


    pdf.showPage()

    pdf.drawString(15, 800, f'Image: {libro.image.url}')
    image = ImageReader(libro.image.path)
    pdf.drawImage(image, 0, 0)

    pdf.save()
    archivo.seek(0)

    reemplazar = f"{libro.title.replace(' ', '_')}.pdf" 
    directorio = os.path.join(reemplazar) 

    with open(f"upload/upload/{directorio}", "wb") as f:
        f.write(archivo.getvalue())

    conexion = sqlite3.connect("db.sqlite3")
    cursor = conexion.cursor()
    rutaPDF = f'upload/{directorio}'
    cursor.execute("UPDATE catalog_book SET pdf=? WHERE id=?", (rutaPDF, pk))
    conexion.commit()
    conexion.close()
    redireccion = request.path.split('/')
    messages.add_message(request=request, level=messages.SUCCESS, message="¡PDF creado!")
    return HttpResponseRedirect('/'.join(redireccion[:4]))

@method_decorator(permission_required('catalog.can_change_book'), name='dispatch')
class BookUpdateView(LoginRequiredMixin, generic.UpdateView):
    model = Book
    fields = "__all__"

@method_decorator(permission_required('catalog.can_delete_book'), name='dispatch')
class BookDeleteView(LoginRequiredMixin, generic.DeleteView):
    model = Book
    success_url = "/catalog/books"


""" 
PÁGINA 6 EN EL DOCUMENTO
"""
""" Autores """

class AuthorListView(generic.ListView):
    model = Author
    paginate_by = 10
    paginate_orphans = 1

    def get_queryset(self):
        resultado = super().get_queryset()
        busqueda = self.request.GET.get("busqueda")
        if busqueda:
            resultado = Author.objects.filter(first_name__icontains=busqueda)
            if not resultado:
                resultado = Author.objects.filter(last_name__icontains=busqueda)
            return resultado
        return super().get_queryset()

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['now'] = timezone.now()
        return context

class AuthorDetailView(generic.DetailView):
    model = Author

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        print(context)
        test = self.kwargs['pk']
        print(test)
        context['books'] = Book.objects.filter(author=self.kwargs['pk'])
        print(context)
        return context
    
@method_decorator(permission_required('catalog.can_add_author'), name='dispatch')
class AuthorCreateView(LoginRequiredMixin, CreateView):
    model = Author
    fields = '__all__'

@method_decorator(permission_required('catalog.can_edit_author'), name='dispatch')
class AuthorUpdateView(LoginRequiredMixin, generic.UpdateView):
    model = Author
    fields = "__all__"

@method_decorator(permission_required('catalog.can_delete_author'), name='dispatch')
class AuthorDeleteView(LoginRequiredMixin, generic.DeleteView):
    model = Author
    success_url = "/catalog/authors"


""" 
PÁGINA 8 EN EL DOCUMENTO
"""
""" JSON """

def respuestaGET(request):
    primero = request.GET.get('primero')
    segundo = request.GET.get('segundo')
    mensaje = {"primero":primero, "segundo":segundo}
    print(primero)
    print(segundo)
    print(mensaje)
    return JsonResponse(mensaje)

def mas(request, id1, id2):
    respuesta = {"campo1":id1, "campo2":id2}
    return JsonResponse(respuesta)


def mas2(request, id):
    if id != 0:
        book = list(Book.objects.filter(pk=id).values())
    else:
        book = list(Book.objects.values())
        
    return JsonResponse(book, safe=False)

def JsonFinder(request):
    return render(request, "JsonFinder.html")


# Examen 10-12-2024 Javier
""" 
PÁGINA 9 EN EL DOCUMENTO
"""
def descarga(request):
    '''
      Fichero .txt a descargar en el enlace con toda la información de los lectores
    '''
    lectores = Lector.objects.all()
    file_data = open("lectores.txt", "w")
    longitud = len(Lector.objects.all())
    file_data.write("Id, DNI, apellidos, nombre, dirección, localidad\n")
    for lector in range(longitud):
        file_data.write(f'''{lectores[lector].id}, {lectores[lector].DNI}, {lectores[lector]}, {lectores[lector].direccion}, {lectores[lector].localidad}\n''')
    file_data.close()
    return HttpResponse("Fichero descargado conteniendo la información")

def descargaEncuesta(request, id):
    '''
      Fichero .txt a descargar en el enlace con toda la información de los lectores
    '''
    Encuestas = Encuesta.objects.get(pk=id)
    file_data = ""
    file_data += "Id, Pregunta, Fecha de Creación, Fecha de Inicio, Fecha de Finalización, Estado\n"
    file_data += f'''{Encuestas.id}, {Encuestas}, {Encuestas.fecha_creacion}, {Encuestas.fecha_inicio}, {Encuestas.fecha_finalizacion}, {Encuestas.estado}\n'''
    fichero = HttpResponse(file_data, content_type='application/text charset=utf-8')
    fichero['Content-Disposition'] = f'attachment; filename="encuesta{Encuestas.id}.txt"'
    conexion = sqlite3.connect("db.sqlite3")
    cursor = conexion.cursor()
    encontrar = cursor.execute("SELECT * FROM catalog_encuesta WHERE id=?", (id, ))
    encontrar = encontrar.fetchone()
    estadoCambio = 0
    if encontrar[1] == "I":
        estadoCambio = cursor.execute("UPDATE catalog_encuesta SET estado=? WHERE id=?", ('P', id))
        estadoCambio = estadoCambio.fetchone()
        conexion.commit()
        conexion.close()
        return fichero
    elif encontrar[1] == "P":
        estadoCambio = cursor.execute("UPDATE catalog_encuesta SET estado=? WHERE id=?", ('C', id))
        estadoCambio = estadoCambio.fetchone()
        conexion.commit()
        conexion.close()
        return HttpResponse("Vuelve atrás y reinicia")
    elif encontrar[1] == "C":
        Respuestas = Respuesta.objects.filter(pregunta_id=id)
        context = {
            'Encuestas': Encuestas,
            'Respuestas': Respuestas,
        }
        return render(request, 'encuesta_detail.html', context=context)
    
class EncuestaDetailView(generic.DetailView):
    model = Encuesta
    
class ListadoEncuestasView(generic.ListView):
    '''

catalog/templates/JsonFinder.html
{% extends "base_generic.html" %}

{% block content %}
    {% load static %}
    <script src="{% static 'bookJson.js' %}" defer></script>
    <h1>Bienvenido, aquí verás cómo funciona el JSON y el Fetch en Django</h1>
    <h1>Revisa la consola</h1>

{% endblock %}

catalog/templates/base_generic.html
<!DOCTYPE html>
<html lang="en">
<head>

  {% block title %}<title>Local Library</title>{% endblock %}
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>

  {% load static %}
  <link rel="stylesheet" href="{% static 'css/styles.css' %}">

</head>

<body>

  <div class="container-fluid">

    <div class="row">
      <div class="col-sm-2">
      {% block sidebar %}
      <ul class="sidebar-nav">
          <li><a href="{% url 'index' %}">Home</a></li>
          <li><a href="{% url 'books' %}">All books</a></li>
          <li><a href="{% url 'authors' %}">All authors</a></li>
          <li><a href="{% url 'albums' %}">All albums</a></li>
          <li><a href="{% url 'lector_list'  %}">Descarga TODOS los lectores sobre un fichero de lectores</a></li>
          <li><a href="{% url 'encuesta_list' %}">Listado de las encuestas</a></li>
          <li><a href="{% url 'calculadora' %}">Calculadora</a></li>
          <br>
          {% if user.is_authenticated %}
            <li>User: {{ user.get_username }}</li>
            <li>Email: {{ user.email }}</li>
            <li>Superuser?: {{ user.is_superuser }}</li>
            <li><a href="{% url 'my-borrowed' %}">Mis libros prestados y reservados</a></li>
            <li><a href="{% url 'albumes-prestados' %}">Mis álbumes prestados y reservados</a></li>
            <li><a href="{% url 'book-create' %}">Crear libro</a></li>
            <li><a href="{% url 'author-create' %}">Dar de alta un autor</a></li>
            <li><a href="{% url 'darAltaUsuarioX' %}">Dar de alta o revisar tu Usuario X</a></li>
            <li><a href="{% url 'formulario' %}">Formulario de Álbumes</a></li>
            <li><a href="{% url 'logouts'%}?next={{request.path}}">Cerrar sesión</a></li>
          {% else %}
            <li><a href="{% url 'login'%}?next={{request.path}}">Iniciar sesión</a></li>
          {% endif %}
      </ul>
     {% endblock %}
      </div>
      <div class="col-sm-10 ">
      {% block content %}{% endblock %}
    <br>
    {% block pagination %}
       {% if is_paginated %}
          <div class="pagination">
              <span class="page-links">
                  {% if page_obj.has_previous %}
                      <a href="{{ request.path }}?page={{ page_obj.previous_page_number }}">anterior</a>
                  {% endif %}
                  <span class="page-current">
                       Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
                  </span>
                  {% if page_obj.has_next %}
                      <a href="{{ request.path }}?page={{ page_obj.next_page_number }}">siguiente</a>
                  {% endif %}
              </span>
          </div>
      {% endif %}
    {% endblock %}
      </div>
    </div>

  </div>
</body>
</html>

catalog/templates/calculadora.html
{% extends "base_generic.html" %}

{% block content %}

{% if limite > 3 and not user.is_superuser %}
<h1>Ya has visitado este sitio más veces de las que podías por hoy</h1>
<h2>¿Quieres más? Compra el Modo Prémium</h2>

{% else %}
<h1>Calculadora</h1>
<h2>Bienvenido, {{user.get_username}} </h2>

<form method="post" action="">
    {% csrf_token %}
    <input name="resultado" value="{{ resultado }}" readonly><br>
    <button type="submit" name="boton" value="7">7</button>
    <button type="submit" name="boton" value="8">8</button>
    <button type="submit" name="boton" value="9">9</button>
    <button type="submit" name="boton" value="/">/</button>
    <br>
    <button type="submit" name="boton" value="4">4</button>
    <button type="submit" name="boton" value="5">5</button>
    <button type="submit" name="boton" value="6">6</button>
    <button type="submit" name="boton" value="*">*</button>
    <br>
    <button type="submit" name="boton" value="1">1</button>
    <button type="submit" name="boton" value="2">2</button>
    <button type="submit" name="boton" value="3">3</button>
    <button type="submit" name="boton" value="-">-</button>
    <br>
    <button type="submit" name="boton" value="0">0</button>
    <button type="submit" name="boton" value="=">=</button>
    <button type="submit" name="boton" value="+">+</button>
</form>

    <h2>Visitas: {{ num_visits }}</h2>

{% endif %}
{% endblock %}

catalog/templates/crudAutor.html
{% extends "base_generic.html" %}

{% block content %}

<hr>

<form action="" method="post">
    {% csrf_token %}
    <table>
    {{ form.as_table }}
    </table>
    <input type="submit" value="Funcionalidad 1" name="funcionalidad1" />
    <input type="submit" value="Funcionalidad 2" name="funcionalidad2"/>
    <input type="submit" value="Funcionalidad 3" name="funcionalidad3" />
</form>

<hr>


{% endblock %}

catalog/templates/darAltaUsuarioX.html
{% extends "base_generic.html" %}

{% block content %}

{% if messages %}
<ul>
  {% for message in messages %}
     <li>{{ message }}</li>
  {% endfor %}
</ul>
{% endif %}

<hr>

    <form action="" method="post">
        {% csrf_token %}
        <table>
        {{ form.as_table }}
        </table>
        {% if request.user.usuariox != "" %}
        <input disabled name="submit" type="submit" value="Dar de alta"/>
        <input name="update" type="submit" value="Editar tu Usuario X"/>
        <input name="delete" type="submit" value="Borrar tu Usuario X"/>
        {% else %}
        <input name="submit" type="submit" value="Dar de alta"/>
        <input disabled name="update" type="submit" value="Editar tu Usuario X"/>
        <input disabled name="delete" type="submit" value="Borrar tu Usuario X"/>
        {% endif %}

    </form>



{% if request.user.usuariox != ""%}
<h1>¡Ya tienes un Usuario X!</h1>
<ol>
    <h2>Nombres: {{ nombres }}</h2>
    <h2>Apellidos: {{ apellidos }}</h2>
    <h2>Correo: {{ correo }}</h2>
    <h2>Dirección: {{ direccion }}</h2>
    <h2>Municipio: {{ municipio }}</h2>
    <h2>Aficiones: {{ aficiones }}</h2>
    <h2>Y, tu usuario del sistema: {{ request.user }}</h2>
</ol>
{% endif %}

<hr>


{% endblock %}

catalog/templates/encuesta_detail.html
{% extends "base_generic.html" %}

{% block content %}

  <h1>Encuesta: {{ Encuestas.pregunta }}</h1>
  <p>ID: {{ Encuestas.id }}</p>
  <p>Estado {{ Encuestas.estado }}</p>
  <p>Fecha de Inicio: {{ Encuestas.fecha_inicio }}</p>
  <p>Fecha de Finalización: {{ Encuestas.fecha_finalizacion }}</p>
  <h1>Respuestas: </h1>
  {% for respuesta in Respuestas %}
    <p>{{ respuesta }} <br> sus votos: {{ respuesta.votos }} </p>
    <br>
  {% endfor %}
  

{% endblock %}

catalog/templates/formulario.html
{% extends "base_generic.html" %}

{% block content %}
<h1>Formulario de Álbumes</h1>

{% if messages %}
<ul>
  {% for message in messages %}
     <li>{{ message }}</li>
  {% endfor %}
</ul>
{% endif %}

<form action="" method="post">
    {% csrf_token %}
    <table>
    {{ form.as_table }}
    </table>
    <input type="submit" value="Submit" />
</form>

{% endblock %}

catalog/templates/index.html
{% extends "base_generic.html" %}

{% block content %}
<h1>Local Library Home</h1>

  <h1>Bienvenido, {{ user }}</h1>

  <p>Welcome to <em>LocalLibrary</em>, a very basic Django website developed as a tutorial example on the Mozilla Developer Network.</p>

<h2>Dynamic content</h2>

  <p>The library has the following record counts:</p>
  <ul><!-- href="{% url 'books' %}" -->
    <li><strong><a href="{% url 'books' %}">Books</a>:</strong> {{ num_books }}</li>
    <li><strong>Copies:</strong> {{ num_instances }}</li>
    <li><strong>Copies available:</strong> {{ num_instances_available }}</li>
    <li><strong><a href="{% url 'authors' %}">Authors</a></strong> {{ num_authors }}</li>
    <li><strong><a href="{% url 'albums' %}">Albums: </a></strong> {{ num_albums }}</li>
    <li><strong>Número de copias de ábumes</strong>: {{ num_albuminst }}</li>
    <li><strong>Número de usuarios</strong>: {{ num_users }}</li>
  </ul>

  <p>Times you've visited this website {{ num_visits }}</p>

  <h2>El árbol de la Librería:</h2>
  <q>El árbol de la vida</q>
  <ul>
    <li><strong>Index</strong>: <a href="{% url 'index' %}">es decir, donde estás actualmente</a></li>
    <li><strong>Libros</strong>: <a href="{% url 'books' %}"">Lista de libros completa</a>, 
                <a href="{% url 'book-detail' pk=1 %}">lista de libros según ID</a>,
                <a href="{% url 'my-borrowed' %}">libros prestados</a>,
                <a href="">formulario de libros</a></li>
    <li><strong>Autores</strong>: <a href="{% url 'authors' %}">Lista de autores</a>, <a href="{% url 'author-detail' pk=1 %}">lista de autores según ID</a></li>
    <li><strong>Álbumes</strong>: <a href="{% url 'albums' %}">lista de álbumes completa</a></li>
    <li><strong>Respuestas con JSON</strong>: <a href="{% url 'respuestaGET' %}">dos campos con JSON</a>, 
      <a href="{% url 'dosJSON' id1=1 id2=2 %}">dos campos con JSON según el enlace</a>,
      <a href="{% url 'librosJSON' id=0 %}">lista de libros según JSON</a>,
      <a href="{% url 'json-finder' %}">JSONFinder: Django con Fetch</a></li>
    <li><strong>El Examen del 10-12-2024</strong>: <a href="{% url 'lector_list' %}">descargar lista de lectores</a>, 
      <a href="{% url 'encuesta_list' %}">lista de encuestas</a></li>
    <li><strong>Calculadora</strong>: <a href="{% url 'calculadora' %}">calculadora</a></li>
    <li><strong>El usuario X</strong>: <a href="{% url 'darAltaUsuarioX' %}">revisar tu Usuario X</a></li>
    <li><strong>Api RESTful</strong>: <a href="{% url 'api:autor-api' %}">revisar los autores en API RESTful</a></li>
    <li><strong>Mi funcionalidad</strong>: <a href="{% url 'reservar' %}">reservar álbumes/libros</a></li>
  </ul>

{% endblock %}

catalog/templates/reserva.html
{% extends "base_generic.html" %}

{% block content %}
{% load static %}
<script src="{% static 'reserva.js' %}" defer></script>
{% if messages %}
<ul>
  {% for message in messages %}
     <li>{{ message }}</li>
  {% endfor %}
</ul>
{% endif %}
<hr>

{% if request.user.usuariox %}
<form action="" method="post">
    {% csrf_token %}

    <table>
    {{ form.as_p }}
    
    </table>
    <input type="submit" value="Entregar" />
</form>
{% else %}
<h1>No tienes un Usuario X. <a href="{% url 'darAltaUsuarioX' %}">Primero tienes que hacerte uno</a>.</h1>
{% endif %}

<hr>


{% endblock %}