api/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include
from django.views.generic import RedirectView
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic import TemplateView
from api import views

app_name = 'api'
urlpatterns = [
    path('autor/', views.autor_api_view, name='autor-api'),
    path('autor/<int:pk>', views.autor_detail_view, name='autor_detail_view'),
]

catalog/urls.py
from django.urls import include, path
from . import views

urlpatterns = [
    path('', views.index, name='index'),

# Libros
    path('books/', views.BookListView.as_view(), name='books'),
    path('book/<int:pk>', views.BookDetailView.as_view(), name='book-detail'),
    path('mybooks/', views.LoanedBooksByUserListView.as_view(), name='my-borrowed'),
    path('book/<uuid:pk>/renew/', views.renew_book_librarian, name='renew-book-librarian'),
    path('book/create/', views.BookCreate.as_view(), name='book-create'),
    path('book/<int:pk>/crearPDF', views.crearPDF, name='crear-pdf'),
    path('book/<int:pk>/update/', views.BookUpdateView.as_view(), name='book-update'),
    path('book/<int:pk>/delete/', views.BookDeleteView.as_view(), name='book-delete'),


# Autores
    path('authors/', views.AuthorListView.as_view(), name='authors'),
    path('author/<int:pk>', views.AuthorDetailView.as_view(), name='author-detail'),
    path('author/create/', views.AuthorCreateView.as_view(), name='author-create'),
    path('author/<int:pk>/update/', views.AuthorUpdateView.as_view(), name='author-update'),
    path('author/<int:pk>/delete/', views.AuthorDeleteView.as_view(), name='author-delete'),
    path('myalbums/', views.AlbumesPrestadosOReservados.as_view(), name='albumes-prestados'),


# JSON
    path('mas/<str:id1>/<str:id2>', views.mas, name='dosJSON'),
    path('mas/<int:id>', views.mas2, name='librosJSON'),
    path('get/', views.respuestaGET, name='respuestaGET'),
    path('JsonFinder/', views.JsonFinder, name='json-finder'),

# Examen 10-12-2024 Javier
    path('listadoLectores/', views.descarga, name='lector_list'),
    path('listadoEncuestas/', views.ListadoEncuestasView.as_view(), name='encuesta_list'),
    path('listadoEncuestas/<int:id>', views.descargaEncuesta, name='descargaEncuesta'),

# Calculadora
    path('calculadora/', views.calculadora, name='calculadora'),

# Álbumes
    path('formulario/', views.formulario, name='formulario'),
    path('albums/', views.AlbumListView.as_view(), name='albums'),
    path('album/<int:pk>', views.AlbumDetailView.as_view(), name='album-detail'),
    path('album/<int:pk>/update/', views.AlbumUpdateView.as_view(), name='album-update'),
    path('album/<int:pk>/delete/', views.AlbumDeleteView.as_view(), name='album-delete'),

# Usuario X
    path('alta/', views.altaUsuarioX, name='darAltaUsuarioX'),
    path('alta/<int:pk>/update/', views.UsuarioXUpdateView.as_view(), name='usuariox-update'),
    path('alta/<int:pk>/delete/', views.UsuarioXDeleteView.as_view(), name='usuariox-delete'),

# API RESTful
    path('v1/api/', include('api.urls', namespace='api')),

# Reserva
    path('reservar/', views.reservar, name='reservar'),


]

locallibrary/urls.py
from catalog import views
from django.contrib import admin
from django.urls import path
from django.urls import include
from django.views.generic import RedirectView
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic import TemplateView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('catalog/', include('catalog.urls')),
    path('', RedirectView.as_view(url='catalog/')),
    path('catalog/', include('catalog.urls')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

urlpatterns += [
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/new-account', views.nuevoUsuario, name="new_account"),
    path('accounts/logouts/', TemplateView.as_view(template_name="registration/logout.html"), name="logouts"),
    path('api/', include('api.urls')),
    path('api-auth/', include('rest_framework.urls'))
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

catalog/models.py
from django.db import models
from django.urls import reverse
from django.utils import timezone
import uuid
from django.contrib.auth.models import User
from datetime import date


# Create your models here.
class UsuarioX(models.Model):
    nombres = models.CharField(max_length=50)
    apellidos = models.CharField(max_length=50)
    correo = models.CharField(max_length=50)
    direccion = models.TextField(max_length=80)
    municipio = models.CharField(max_length=100, blank=True, null=True)
    aficiones = models.TextField(max_length=80)

    usuario = models.OneToOneField(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.nombres + " " + self.apellidos


class Genre(models.Model):
    """
    Modelo que representa un género literario (p. ej. ciencia ficción, poesía, etc.).
    """
    name = models.CharField(max_length=200, help_text="Teclea un género de libro")

    def __str__(self):
        """
        Cadena que representa a la instancia particular del modelo (p. ej. en el sitio de Administración)
        """
        return self.name

class Author(models.Model):
    """
    Modelo que representa un autor
    """
    first_name = models.CharField(max_length=100)
    last_name = models.CharField(max_length=100)
    date_of_birth = models.DateField(null=True, blank=True)
    date_of_death = models.DateField('Died', null=True, blank=True)

    def get_absolute_url(self):
        """
        Retorna la url para acceder a una instancia particular de un autor.
        """
        return reverse('author-detail', args=[str(self.id)])


    def __str__(self):
        """
        String para representar el Objeto Modelo
        """
        return '%s, %s' % (self.last_name, self.first_name)

class Language(models.Model):

    name = models.CharField(max_length=20, help_text="Escoja idioma")

    def __str__(self):
        return self.name

class Book(models.Model):
    """
    Modelo que representa un libro (pero no un Ejemplar específico).
    """

    title = models.CharField(max_length=200)

    author = models.ForeignKey('Author', on_delete=models.SET_NULL, null=True)
    # ForeignKey, ya que un libro tiene un solo autor, pero el mismo autor puede haber escrito muchos libros.
    # 'Author' es un string, en vez de un objeto, porque la clase Author aún no ha sido declarada.

    summary = models.TextField(max_length=1000, help_text="Ingrese una breve descripción del libro")

    isbn = models.CharField('ISBN',max_length=13, help_text='13 Caracteres <a href="https://www.isbn-international.org/content/what-isbn">ISBN number</a>')

    genre = models.ManyToManyField(Genre, help_text="Seleccione un genero para este libro")
    # ManyToManyField, porque un género puede contener muchos libros y un libro puede cubrir varios géneros.
    # La clase Genre ya ha sido definida, entonces podemos especificar el objeto arriba.

    language = models.ForeignKey('Language', on_delete=models.SET_NULL, null=True)

    image = models.ImageField(default='overkill.jpg', upload_to='upload/', null=True, blank=True)

    video = models.FileField(upload_to='upload/', null=True, blank=True)

    pdf = models.FileField(upload_to='upload/', null=True, blank=True)
    def __str__(self): 
        """
        String que representa al objeto Book
        """
        return self.title


    def get_absolute_url(self):
        """
        Devuelve el URL a una instancia particular de Book
        """
        return reverse('book-detail', args=[str(self.id)])

    def display_genre(self):
        """
        Creates a string for the Genre. This is required to display genre in Admin.
        """
        return ', '.join([ genre.name for genre in self.genre.all()[:3] ]) 
    display_genre.short_description = 'Genre'


class BookInstance(models.Model):
    """
    Modelo que representa una copia específica de un libro (i.e. que puede ser prestado por la biblioteca).
    """
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, help_text="ID único para este libro particular en toda la biblioteca")
    book = models.ForeignKey('Book', on_delete=models.SET_NULL, null=True)
    imprint = models.CharField(max_length=200)
    whenWasItBooked = models.DateField(default=timezone.now, null=True, blank=True)
    due_back = models.DateField(null=True, blank=True)

    LOAN_STATUS = (
        ('m', 'Maintenance'),
        ('o', 'On loan'),
        ('a', 'Available'),
        ('r', 'Reserved'),
    )

    status = models.CharField(max_length=1, choices=LOAN_STATUS, blank=True, default='m', help_text='Disponibilidad del libro')
    borrower = models.ForeignKey(UsuarioX, on_delete=models.SET_NULL, null=True, blank=True)

    class Meta:
        ordering = ["due_back"]
        permissions = (("can_mark_returned", "Set book as returned"),)


    def __str__(self):
        """
        String para representar el Objeto del Modelo
        """
        return '%s (%s)' % (self.id,self.book.title)

    @property
    def is_overdue(self):
        if self.due_back and date.today() > self.due_back:
            return True
        return False

# Ejercicio Javi

class UserX(models.Model):
    username = models.CharField(max_length=100)
    email = models.CharField(max_length=100)

    def __str__(self):
        return self.username

class PublisherX(models.Model):
    firstname = models.CharField(max_length=100)
    lastname = models.CharField(max_length=100)
    recommendedby = models.ForeignKey('PublisherX', on_delete=models.CASCADE, null=True, blank=True)
    joindate = models.DateField()
    popularity_score = models.IntegerField()

    def __str__(self):
        return self.firstname + ' ' + self.lastname



class AuthorX(models.Model):
    firstname = models.CharField(max_length=100)
    lastname = models.CharField(max_length=100)
    address = models.CharField(max_length=200, null=True)
    zipcode = models.IntegerField(null=True)
    telephone = models.CharField(max_length=100, null=True)
    recommendedby = models.ForeignKey('AuthorX', on_delete=models.CASCADE, related_name='recommended_authors', related_query_name='recommended_authors', blank=True, null=True)
    joindate = models.DateField()
    popularity_score = models.IntegerField()
    followers = models.ManyToManyField('UserX', related_name='followed_authors', related_query_name='followed_authors')

    def __str__(self):
        return self.firstname + ' ' + self.lastname

class BooksX(models.Model):
    title = models.CharField(max_length=100)
    genre = models.CharField(max_length=200)
    price = models.IntegerField(null=True)
    published_date = models.DateField()
    author = models.ForeignKey('AuthorX', on_delete=models.CASCADE, related_name='books', related_query_name='books')
    publisher = models.ForeignKey('PublisherX', on_delete=models.CASCADE, related_name='books', related_query_name='books')

    def __str__(self):
        return self.title


# Examen 10-12-2024 Javier

class Lector(models.Model):
    DNI = models.CharField(max_length=9, help_text="Ocho letras para acabar en una letra mayúscula")
    nombre = models.CharField(max_length=15)
    apellidos = models.CharField(max_length=30)
    direccion = models.CharField(max_length=50, null=True)
    localidad = models.CharField(max_length=50, null=True)
    clave = models.CharField(max_length=32, null=True, blank=True)

    def __str__(self):
        return self.apellidos + ", " + self.nombre

class Encuesta(models.Model):
    pregunta = models.TextField(max_length=200)

    fecha_creacion = models.DateField(default=timezone.now)
    fecha_inicio = models.DateField(null=True, blank=True)
    fecha_finalizacion = models.DateField(null=True, blank=True)

    tipos_estado = (
        ('I', 'Inicial'),
        ('P', 'Proceso'),
        ('C', 'Cerrada'),
    )
    estado = models.CharField(max_length=1, choices=tipos_estado, default='I')

    def __str__(self):
        return self.pregunta

class Respuesta(models.Model):
    pregunta = models.ForeignKey(Encuesta, on_delete=models.CASCADE)
    respuesta = models.CharField(max_length=200)
    votos = models.IntegerField(default=0)

    def __str__(self):
        return self.respuesta

from django.contrib.auth.models import *



class Banda(models.Model):
    nombre = models.CharField(max_length=80)

    def __str__(self):
        return self.nombre

class Discografica(models.Model):
    nombre = models.CharField(max_length=50)

    def __str__(self):
        return self.nombre

class Album(models.Model):
    nombre = models.CharField(max_length=50)
    banda = models.ForeignKey(Banda, on_delete=models.CASCADE)

    tiposDeAlbumes = (
        ('EP', 'Extended Playlist'),
        ('LP', 'Long Playlist'),
    )
    tipo = models.CharField(max_length=2, choices=tiposDeAlbumes, default='LP')

    fechaDePublicacion = models.DateField(blank=True, null=True)
    nacionalidad = models.CharField(max_length=30)
    discografica = models.ForeignKey(Discografica, on_delete=models.CASCADE)
    
    formatosDeAlbumes = (
        ('DVD', 'DVD'),
        ('VHS', 'VHS'),
        ('CD', 'Compact Disk'),
    )
    formato = models.CharField(max_length=3, choices=formatosDeAlbumes, default='DVD')
    canciones = models.IntegerField()
    portada = models.FileField(upload_to='upload/', null=True, blank=True)
    recomendable = models.BooleanField(default=False)
    enlaceEnMetallum = models.URLField(null=True, blank=True)
    notasAdicionales = models.TextField(max_length=1000)

    def __str__(self):
        return self.nombre
    
    def get_absolute_url(self):
        return reverse('album-detail', args=[str(self.id)])

class AlbumInstance(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4)
    album = models.ForeignKey('Album', on_delete=models.SET_NULL, null=True)
    descripcion = models.CharField(max_length=200)
    cuandoSeReservo = models.DateField(default=timezone.now, null=True, blank=True)
    caducidad = models.DateField(null=True, blank=True)

catalog/templates/catalog/album_confirm_delete.html
{% extends "base_generic.html" %}

{% block content %}
<form method="post">{% csrf_token %}
    <p>Are you sure you want to delete "{{ object }}"?</p>
    {{ form }}
    <input type="submit" value="Confirm">
</form>

{% endblock %}

catalog/templates/catalog/album_detail.html
{% extends "base_generic.html" %}

{% block content %}
<ul>
    <li><h1>Nombre: {{album.nombre}}</h1></li>
    <li><h1>Banda: {{album.banda}}</h1></li>
    <li><h1>Tipo de álbum: {{album.tipo}}</h1></li>
    <li><h1>Fecha de publicación: {{album.fechaDePublicacion}}</h1></li>
    <li><h1>Nacionalidad: {{album.nacionalidad}}</h1></li>
    <li><h1>Discográfica: {{album.discografica}}</h1></li>
    <li><h1>Formato de álbum: {{album.formato}}</h1></li>
    <li><h1>Canciones: {{album.canciones}}</h1></li>

    {% if album.portada %}
    <li><h1>Portada: <img src="{{album.portada.url}}"></h1></li>
    {% endif %}

    {% if album.recomendable %}
    <li><h1>¿Recomendable?: Sí</h1></li>
    {% else %}
    <li><h1>¿Recomendable?: No</h1></li>
    {% endif %}

    {% if album.enlaceEnMetallum %}
    <li><h1>Enlace a su página en Metallum: <a href="{{album.enlaceEnMetallum}}">{{album.enlaceEnMetallum}}</a></h1></li>
    {% endif %}

    <li><h1>Notas adicionales: {{album.notasAdicionales}}</h1></li>

    <a href="{% url 'album-update' album.id %}"><button>Editar el Álbum</button></a>
    <a href="{% url 'album-delete' album.id %}"><button>Borrar el álbum</button></a>
    <a href="{% url 'reservar' %}"><button>¡Reserva!</button></a>
</ul>
    <h2>¿Otras recomendaciones de la misma banda?</h2>

    {% for recomendacion in recomendaciones %}
        {% if recomendacion.id != album.id %}
    <h2><a href="{%url 'album-detail' recomendacion.id %}">{{recomendacion}}</a></h2>
        {% endif %}
    {% endfor %}

{% endblock %}

catalog/templates/catalog/album_form.html
{% extends "base_generic.html" %}

{% block content %}

{% if messages %}
<ul>
  {% for message in messages %}
     <li>{{ message }}</li>
  {% endfor %}
</ul>
{% endif %}

<form action="" method="post">
    {% csrf_token %}
    <table>
    {{ form.as_table }}
    </table>
    <input type="submit" value="Submit" />

</form>

{% if form.errors %}
    <div class="errorlist">
        <ul>
        {% for field in form %}
            {% for error in field.errors %}
                <li>{{ error }}</li>
            {% endfor %}
        {% endfor %}
        </ul>
    </div>
{% endif %}
{% endblock %}

catalog/templates/catalog/album_list.html
{% extends "base_generic.html" %}

{% block content %}
    <h1>Lista de álbumes</h1>
    <form method="GET">
      <input type="text" name="busqueda" placeholder="¡Búscame!" value="{{ busqueda }}">
      <button type="submit">Buscar</button>
    </form>
    {% if album_list %}
    <ul>

      {% for album in album_list %}
      <li> <a href="{{album.get_absolute_url}}">{{ album.nombre }}</a>, {{ album.banda }} </li>
      {% endfor %}

    </ul>

    <p>¿Lista paginada? {{ is_paginated }}</p>
    <p>Fecha actual: {{ now }}</p>
    {% else %}
      <p>No hay libros en la biblioteca. {{ num_albums }}</p>
    {% endif %}
    <a href="{% url 'formulario' %}">Añadir álbum</a>
{% endblock %}

catalog/templates/catalog/albuminstance_lista_alquilados.html
{% extends "base_generic.html" %}

{% block content %}
    <h1>Libros prestados y reservados</h1>

    {% if albuminstance_list %}
    <ul>

      {% for albuminst in albuminstance_list %}
      <li class="{% if bookinst.is_overdue %}text-danger{% endif %}">
        <a href="{% url 'album-detail' albuminst.album.pk %}">{{albuminst.album.nombre}}</a> ({{ albuminst.caducidad }})
      </li>
      {% endfor %}
    </ul>

    {% else %}
      <p>No hay libros prestados.</p>
    {% endif %}
{% endblock %}

catalog/templates/catalog/author_confirm_delete.html
{% extends "base_generic.html" %}

{% block content %}
<form method="post">{% csrf_token %}
    <p>Are you sure you want to delete "{{ object }}"?</p>
    {{ form }}
    <input type="submit" value="Confirm">
</form>

{% endblock %}

catalog/templates/catalog/author_form.html
{% extends "base_generic.html" %}

{% block content %}

{% if messages %}
<ul>
  {% for message in messages %}
     <li>{{ message }}</li>
  {% endfor %}
</ul>
{% endif %}

<form action="" method="post">
    {% csrf_token %}
    <table>
    {{ form.as_table }}
    </table>
    <input type="submit" value="Submit" />

</form>
{% endblock %}

catalog/templates/catalog/author_list.html
{% extends "base_generic.html" %}

{% block content %}
    <h1>Lista de autores</h1>
    <form method="GET">
      <input type="text" name="busqueda" placeholder="¡Búscame!" value="{{ busqueda }}">
      <button type="submit">Buscar</button>
    </form>
    {% if author_list %}
    <ul>

      {% for author in author_list %}
      <li>
        <a href="{{ author.get_absolute_url }}">{{ author.last_name }}</a> ({{author.first_name}})
      </li>
      {% endfor %}

    </ul>
    <p>¿Lista paginada? {{ is_paginated }}</p>
    <p>Fecha actual: {{ now }}</p>
    {% else %}
      <p>No hay autores en la biblioteca.</p>
    {% endif %}
    <a href="{% url 'author-create' %}">Añadir autor</a>
{% endblock %}

catalog/templates/catalog/author_update_form.html
<form method="post">{% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Update">
</form>

catalog/templates/catalog/book_detail.html
{% extends "base_generic.html" %}

{% block content %}
{% if messages %}
<ul>
  {% for message in messages %}
     <li>{{ message }}</li>
  {% endfor %}
</ul>
{% endif %}
  <h1>Title: {{ book.title }}</h1>

  <p><strong>Autor:</strong>  <a href="{% url 'author-detail' book.author.pk %}"><strong>{{ book.author }}</strong></a></p> <!-- enlace de detalle del autor aún no definido -->
  <p><strong>Resumen:</strong> {{ book.summary }}</p>
  <p><strong>ISBN:</strong> {{ book.isbn }}</p>
  <p><strong>Idioma:</strong> {{ book.language }}</p>
  <p><strong>Genero:</strong> {% for genre in book.genre.all %} {{ genre }}{% if not forloop.last %}, {% endif %}{% endfor %}</p>
    {% if book.image %}
  <p><strong>Cubierta: </strong> <img src="{{ book.image.url }}" alt="{{ book.title }}"></p>
  <p><strong><a href="{% url 'crear-pdf' book.id %}">Crear PDF</a></strong></p>
   {% endif %}
   {% if book.video %}
  <p><strong>Video: </strong> <video controls>
    <source src="{{ book.video.url }}" type="video/mp4">
    Tu navegador no soporta tanta esencia
  </video></p>
    {% endif%}

    {% if book.pdf %}
  <p><strong>PDF: </strong>  <embed src="{{ book.pdf.url }}" type="application/pdf" width="800" height="1000"></p>
    {% endif %}
   

  <div style="margin-left:20px;margin-top:20px">
    <h4>Copias</h4>

    {% for copy in book.bookinstance_set.all %}
    <hr>
    <p class="{% if copy.status == 'a' %}text-success{% elif copy.status == 'm' %}text-danger{% else %}text-warning{% endif %}">{{ copy.get_status_display }}</p>
    {% if copy.status != 'a' %}<p><strong>Pendiente de devolución:</strong> {{copy.due_back}}</p>{% endif %}
    <p><strong>Imprimir:</strong> {{copy.imprint}}</p>
    <p class="text-muted"><strong>Id:</strong> {{copy.id}}</p>
    {% endfor %}
  </div>
  <a href="{% url 'book-update' book.id %}"><button>Editar el Libro</button></a>
  <a href="{% url 'book-delete' book.id %}"><button>Borrar el Libro</button></a>
  <a href="{% url 'reservar' %}"><button>¡Reserva!</button></a>
{% endblock %}

catalog/templates/catalog/book_form.html
{% extends "base_generic.html" %}

{% block content %}

{% if messages %}
<ul>
  {% for message in messages %}
     <li>{{ message }}</li>
  {% endfor %}
</ul>
{% endif %}

<form action="" method="post">
    {% csrf_token %}
    <table>
    {{ form.as_table }}
    </table>
    <input type="submit" value="Submit" />

</form>
{% endblock %}

catalog/templates/catalog/bookinstance_list_borrowed_user.html
{% extends "base_generic.html" %}

{% block content %}
    <h1>Libros prestados y reservados</h1>

    {% if bookinstance_list %}
    <ul>

      {% for bookinst in bookinstance_list %}
      <li class="{% if bookinst.is_overdue %}text-danger{% endif %}">
        <a href="{% url 'book-detail' bookinst.book.pk %}">{{bookinst.book.title}}</a> ({{ bookinst.due_back }})
        {% if perms.catalog.can_mark_returned %}- <a href="{% url 'renew-book-librarian' bookinst.id %}">Renew</a>  {% endif %}
      </li>
      {% endfor %}
    </ul>

    {% else %}
      <p>No hay libros prestados.</p>
    {% endif %}
{% endblock %}

catalog/templates/catalog/usuariox_confirm_delete.html
{% extends "base_generic.html" %}

{% block content %}
<form method="post">{% csrf_token %}
    <p>Are you sure you want to delete "{{ object }}"?</p>
    {{ form }}
    <input type="submit" value="Confirm">
</form>

{% endblock %}

catalog/templates/catalog/usuariox_form.html
{% extends "base_generic.html" %}

{% block content %}

{% if messages %}
<ul>
  {% for message in messages %}
     <li>{{ message }}</li>
  {% endfor %}
</ul>
{% endif %}

<form action="" method="post">
    {% csrf_token %}
    <table>
    {{ form.as_table }}
    </table>
    <input type="submit" value="Submit" />

</form>

{% if form.errors %}
    <div class="errorlist">
        <ul>
        {% for field in form %}
            {% for error in field.errors %}
                <li>{{ error }}</li>
            {% endfor %}
        {% endfor %}
        </ul>
    </div>
{% endif %}
{% endblock %}